[package]
name = "lighthouse"
version = "0.1.0"
authors = ["Finnkauski <iwiivi@gmail.com>"]
description="Command line tool and Philips Hue light control framework wrapping up the Hue API"
license="AGPL-3.0-or-later"
homepage="https://finnkauski.com"
documentation="https://docs.rs/lighthouse/"
repository="https://github.com/finnkauski/lighthouse"
edition = "2018"
readme="README.md"

[dependencies]
serde = {version = "1.0.104", features = ["derive"]}
serde_json = "1.0.47"
reqwest = {version = "0.10.1", features = ["blocking", "json"] }
dirs = "2.0.2"
dotenv = "0.15.0"
ssdp = "0.7.0"
clap = "2.33.0"
palette = "0.5.0"


[[bin]]
name = "lh"
path = "src/bin/lighthouse.rs"
